### ISSUE TITLE
No Flushing for less 63mm³

### ISSUE THREAD

**Issue by UBaer21** [bambulab/BambuStudio#4738] opened 2024-09-01 22:05 UTC
### Bambu Studio Version

1.9.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

windows 10

### Printer

P1S

### How to reproduce

two Objects different color - print per object - flush volume 50mm³

### Actual results

; FLUSH_START
M400
M109 S220
G1 E2 F523 ;Compensate for filament spillage during waiting temperature
; FLUSH_END

### Expected results

Flushing 50mm³

Also no warning if you mix ASA and PLA on the same plate

### Project file & Debug log uploads

[Untitled50Flush.gcode.3mf.zip](https://github.com/user-attachments/files/16830622/Untitled50Flush.gcode.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by XunZhangBambu** [comment] 2024-09-11 04:01
@UBaer21  Thanks, it's a bug and we have found the root cause. Will be fixed soon

**Closed** 2024-10-09 04:19 UTC
Labels: bug
