### ISSUE TITLE
App crash during painting mode

### ISSUE THREAD

**Issue by darkneon2002** [bambulab/BambuStudio#3480] opened 2024-01-25 16:43 UTC
### Bambu Studio Version

1.8.4..51

### Where is the application from?

Bambu Lab Official website

### OS version

win 11 x64

### Additional system information

i7-14700KF, RTX2080Ti 11GB, 64GB DDR5

### Printer

P1S

### How to reproduce

import multiple models on a single plate
select 1 object
open painting mode
SHIFT + Left Mouse on the object list that "should" select all or multiple objects

https://github.com/bambulab/BambuStudio/assets/10987492/46007720-8274-473d-be2c-728072d7a698

### Actual results

Bambu Studio will hard crash

### Expected results

A message that selecting multiple models during painting is not possible or
it will work (would not expect this) or
nothing if it's not possible

### Project file & Debug log uploads

[paint to crash.zip](https://github.com/bambulab/BambuStudio/files/14055555/paint.to.crash.zip)
[crash_Thu_Jan_25_16_42_39_0.zip](https://github.com/bambulab/BambuStudio/files/14055572/crash_Thu_Jan_25_16_42_39_0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment] 2024-01-30 08:00
@darkneon2002  Is this bug reproducible stably, or does it only appear this once?

**Comment by darkneon2002** [comment] 2024-01-30 12:38
yes very stable bug, I reproduced it on various projects with multiple objects.

**Comment by darkneon2002** [comment] 2024-01-30 12:48
very stable and reproducible

https://github.com/bambulab/BambuStudio/assets/10987492/584720f9-b8ae-4c17-986c-266fc5513f3e

**Comment by zhimin-zeng-bambulab** [comment] 2024-01-31 01:23
We do not support selecting multiple objects for painting at the same time. We will limit this behavior and resolve the crash caused by this operation in the next version.

**Comment by Haidiye00** [comment] 2024-03-01 01:06
This issue has been fixed. Multiple model_object selections have been disabled in the Paint mode. Please wait for version v1.9. Thank you

**Comment by zhimin-zeng-bambulab** [comment] 2024-03-29 07:38
It has been fixed in v01.09.00.60, you can have a try

**Closed by zhimin-zeng-bambulab** 2024-03-29 07:38 UTC
Labels: bug
