### ISSUE TITLE
BUG Open 3MF or STL MacOS 10.15.7

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#513] opened 2022-10-26 01:23 UTC
If I double click the 3mf it doesn't open in any program even though its told to open in BambuStudio, BambuStudio does become the active window but it acts like it doesn't know what to do with the file and just drops it, if I drag and drop the file onto the icon in the dock with BambuStudio open nothing happens, the only way to import is to move the BambuStudio application to one side and drop it onto the build plate but this only works if your on the Prepare Screen...

**Comment by Benderrodrigu3z** [comment] 2022-10-27 17:59
ps this is not a new issue, I just finally got annoyed with it and thought to speak up.

**Comment by bambu123** [comment] 2022-10-31 01:03
Thanks for your feedback. I think it may be the issue with low MacOS version.

**Comment by Benderrodrigu3z** [comment] 2022-10-31 04:37
> Thanks for your feedback. I think it may be the issue with the low MacOS version. We'll check it soon.

not sure how, other programs open properly when you double click the file or drag it to the icon in the dock for that program

**Comment by bambu123** [comment] 2022-11-03 02:59
Double-click the 3mf file when one instance of Bambu Studio opens, and see what happens.

**Comment by Benderrodrigu3z** [comment] 2022-11-03 04:23
Nothing that’s the issue

Sincerely,
Shane F

**Comment by bambu123** [comment] 2022-11-10 01:24
We use a virtual machine to install macOS 10.15.7 but can't reproduce it.
What version of Bambu Studio are you using? make sure to use the latest version.

**Comment by Benderrodrigu3z** [comment] 2022-11-10 02:20
So the newest version made the print menu work better with the vpn on but still small issues with the server on first send. Version 1.3.0.25

Sincerely,
Shane F

**Comment by bambu123** [comment] 2022-11-10 02:33
So that's a new issue. What about the 3mf assosiation problem?

**Comment by Benderrodrigu3z** [comment] 2022-11-10 04:49
Oh sorry I have another ticket open on that issue too, got them flipped in my head

Sincerely,
Shane F

**Comment by bambu123** [comment] 2022-11-16 11:51
@Benderrodrigu3z  So does the problem continue to exist?
Please help send me the app log if it continues.
You can locate the log directory from the menu " Help > Show Configuration Folder" in Bambu Studio.
The log should have these lines when it works.
-------------------------------------------------------
2022-11-16 19:42:53.550596[Thread 0x0000000130a09600]:finished the gui app init
2022-11-16 19:42:53.551684[Thread 0x0000000130a09600]:MacOpenFiles, open files, size 1

**Comment by bambu123** [comment] 2022-11-17 04:01
As you said "even though its told to open in BambuStudio, BambuStudio does become the active window but it acts like it doesn't know what to do with the file and just drops it", Open using BambuStudio force will open BambuStudio, this way there may be some helpful log.

**Comment by bambu123** [comment] 2022-11-17 04:16
Please do not worry. Just try doing some thing with 3mf opening and send us the log.

**Comment by bambu123** [comment] 2023-02-02 10:00
@Benderrodrigu3z 
Does the problem continue to exist? We need your help. Any log is helpful.

**Comment by Benderrodrigu3z** [comment] 2023-03-11 17:53
yes its still an issue, it doesn't even switch to the active screen where the slicer is on open when its defaulted to opening BS program on double click

**Comment by Benderrodrigu3z** [comment] 2023-03-11 17:55
double clicking doesn't do it, dragging it to the dock icon doesn't do anything either, only dragging it to the build plate works

**Comment by bambu123** [comment] 2023-03-13 01:03
Please send us the logs which can be fetched from the configuration folder.
From the menu "Help-> Show Configuration Folder", you can find them.

**Comment by Benderrodrigu3z** [comment] 2023-03-13 05:19
there is no logs on a file not opening, the Mac doesn't even switch screens to the one where bambu is currently open on

**Comment by Benderrodrigu3z** [comment] 2023-03-13 05:23
so when I make 1.5 the default it switches back to the oldest version that I have on file

![Screen Shot 2023-03-13 at 12 22 28 AM](https://user-images.githubusercontent.com/48887257/224614683-548455dd-93f1-4653-b5f8-aee17379df50.png)

**Comment by Benderrodrigu3z** [comment] 2023-03-13 05:24
even with always open with on the right click menu it defaults back to the oldest version
looks like the newer versions don't take presidency

**Comment by Benderrodrigu3z** [comment] 2023-03-13 05:26
if I move 1.3.0.12 to the trash it then defaults to 1.3.0.25 and upon bringing 1.3.0.12 out of the trash that then becomes the default

**Comment by Benderrodrigu3z** [comment] 2023-03-13 05:29
after removing all but 1.3.1.1 and 1.5 the Menu Bar says Bambu Studios on double click but still Doesnt switch the to the active window or open in the app, on removal of 1.3.1.1. it does the same thing to 1.5

**Comment by bambu123** [comment] 2023-03-13 08:09
What's your OS version? The problem may relate to the system because I can't reproduce it here.

BTW:
The default app also stays old on my computer. please remove the old ones when you install the new version, using the 'Replace' not 'Keep Both' option is suggested.
Please do not rename BambuStudio, you can move it to another folder, but do not change its name. The 'New Window' file menu depends on the app name.

**Comment by Benderrodrigu3z** [comment] 2023-03-13 14:05
Scale and Rotate don't listen to the Reset of ZXY
However the Move Command does, see colored markers in pics to understand better

![Screen Shot 2023-03-13 at 9 04 11 AM](https://user-images.githubusercontent.com/48887257/224725075-3eea79ed-ee68-427b-bdba-83299afde383.png)
![Screen Shot 2023-03-13 at 9 04 00 AM](https://user-images.githubusercontent.com/48887257/224725079-8ed7d9a6-7974-4518-acef-7cb136ecdfb9.png)
![Screen Shot 2023-03-13 at 9 03 53 AM](https://user-images.githubusercontent.com/48887257/224725084-6b2fcf3a-90c0-4e71-99b4-e29f4519b343.png)

**Comment by Benderrodrigu3z** [comment] 2023-03-13 14:09
I rename it for Version number, things work faster on 1.3.1.1 then they do now
storing it as a zip for now though so it defaults to the new but it still doesn't cause it to switch screens and open even with that override app in System Preferences that I showed above

![Screen Shot 2023-03-13 at 9 09 19 AM](https://user-images.githubusercontent.com/48887257/224726348-98d40130-e545-4b9c-9bb4-5735c8ec64d4.png)

**Comment by bambu123** [comment] 2023-03-14 00:59
BambuStudio 1.3.0.12 always opens the new file in the new instance. But it failed to start a new instance because the app is renamed. It seems to do nothing.
BambuStudio 1.5.0.60 opens the STLs in the current window. It is successful.

Is this your problem?

**Comment by Benderrodrigu3z** [comment] 2023-03-14 19:10
I would assume so, is there a way to have the app renamed like you can rename any other app on the Mac and it still would use it?Sincerely,Shane FSent from my iPhone13On Mar 13, 2023, at 7:59 PM, cmguo ***@***.***> wrote:﻿
BambuStudio 1.3.0.12 always opens the new file in the new instance. But it failed to start a new instance because the app is renamed. It seems to do nothing.
BambuStudio 1.5.0.60 opens the STLs in the current window. It is successful.
Is this your problem?

**Comment by bambu123** [comment] 2023-03-15 00:37
If that's the rename problem, we can fix it.

**Comment by Benderrodrigu3z** [comment] 2023-03-15 04:12
I haven’t tested thisSincerely,Shane FSent from my iPhone13On Mar 14, 2023, at 7:37 PM, cmguo ***@***.***> wrote:﻿
If that's the rename problem, we can fix it.

**Comment by bambu123** [comment] 2023-04-23 10:30
Fixed in version 1.6, please have a try.

**Closed** 2023-08-23 09:41 UTC
Labels: bug
