### ISSUE TITLE
Bridges printed that don't support anything

### ISSUE THREAD

**Issue by LonelyFarts** [bambulab/BambuStudio#4963] opened 2024-10-09 03:33 UTC
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

13th Gen Intel(R) Core(TM) i7-13700F   2.10 GHz 32.0 GB (31.8 GB usable) 32.0 GB (31.8 GB usable)

### Printer

P1P

### How to reproduce

Look at the project file

### Actual results

bridges printed where there is no reason for bridges to be printed.

### Expected results

Don't print pointless bridges that support nothing.

### Project file & Debug log uploads

[dumb bridges.zip](https://github.com/user-attachments/files/17301541/dumb.bridges.zip)

[log.zip](https://github.com/user-attachments/files/17301618/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by LonelyFarts** [comment] 2024-10-09 03:40
I found a solution. Set the modifier object's "Wall loops"=0

**Comment by ttt888zzz** [comment] 2024-10-10 01:15
HI [LonelyFarts](https://github.com/LonelyFarts)：Please follow the steps below to enable the support option
![20241010091311_rec_](https://github.com/user-attachments/assets/3752c493-0d1b-4133-83cb-f3f70adbdb41)

**Comment by tangketan** [comment] 2024-10-10 01:39
> I found a solution. Set the modifier object's "Wall loops"=0

Yes, that's a good solution. Issue closed as it's not a bug.

**Closed by tangketan** 2024-10-10 01:39 UTC
Labels: bug
