### ISSUE TITLE
Saved projects reopen with changed object size

### ISSUE THREAD

**Issue by TomtheRom** [bambulab/BambuStudio#1825] opened 2023-05-19 15:52 UTC
I create a project with modified and duplicated parts (1 original 4 duplicates) and print them successfully.
After that I safe toe project for future use.

Whe Ireopen the project the 4 duplicates are way oversized and are bigger than the print plate.
Only solution is to delete the duplicates and duplicate them again

**Expected behavior**
The size of the duplicates shall not vary when the project i reopened

**Screenshots**
![image](https://github.com/bambulab/BambuStudio/assets/134083372/bd0a2468-3610-4f37-a5fe-a09c65d29c41)

**Comment by lanewei120** [comment] 2023-05-22 01:10
@TomtheRom 
hello, thanks for reporting this issue

which bambustudio version are you using?
and could you share the 3mf with your described issue to us?
upload here or send us an email

**Comment by TomtheRom** [comment] 2023-05-22 10:50
Thanks for coming back to my problem.

My BambuStudio Version is the actual one, I just updated some days ago:

![image](https://github.com/bambulab/BambuStudio/assets/134083372/052489a7-1328-4fce-816f-1c75038649b9)


I attached the actual 3mf file (worked in the meantime with it and needed it to print a new set) in as ZIP container because it's not possible to attach 3mf directly.

Best regards
Tomthe Rom
[Din_Caps.zip](https://github.com/bambulab/BambuStudio/files/11530129/Din_Caps.zip)

**Comment by bambu123** [comment] 2023-05-22 11:47
Which language are you using?
Could you please send me the abnormal 3mf instead of the normal one?

**Comment by TomtheRom** [comment] 2023-05-22 14:09
I use the German Language

And I sent you the 3MF only file which I have/use - the one behaves the way I described it.

So probably we are on track already - if you could open it withut the phenomena I have then probably there is a Problem with the German version of the BambuLab Studio.

Is there a possibilty to try the English version parallel to the German version - I will try this this evening (English is not really a problem for me)

**Comment by TomtheRom** [comment] 2023-05-22 15:46
Hi there

I just tested different preferences and I think I found the location of the bug.

Repedetly when I loin at BambuStudio in Region 'Europe' the bug happens, in German as in English language.

If I switch Region to 'Others' - the file oppens as expected.


My personal workaround for now will be:

Language: German
Region: Others

Best Regards from Switzerland
TomtheRom

**Comment by bambu123** [comment] 2023-05-23 00:47
Glad to hear that!
But I am sorry I can't reproduce it yet.
Can you send me a 3mf file with the problem?

**Comment by TomtheRom** [comment] 2023-05-23 18:20
Thanks for replying

Have you changed the properties of Bambu Studio to German Langage and
Region Europe?

With these settings I have the problem with the 3mf file I already sent
you.

Keep in mind,  that my PC runs with region settings German (Switzerland)
I assume an issue with the decimal separator in the German settings of
BambuStudio. In German speaking countys the comma is used as decimal
sepaator.... except in Switzerland.. . we use the point as decimal
separator.
If the properties in BambuStudio assume a comma, this might be the source
of the issue.

Best regards
Tomthe Rom

cmguo ***@***.***> schrieb am Di., 23. Mai 2023, 02:48:

**Comment by bambu123** [comment] 2023-05-29 05:34
Thank you for adding more details. I'll check that.

**Comment by bambu123** [comment] 2023-07-11 07:24
Close as fixed in the 1.7 beta version.

**Closed by bambu123** 2023-07-11 07:24 UTC
Labels: bug
