### ISSUE TITLE
BambuStudio doesn't seem to comprehend nested models

### ISSUE THREAD

**Issue by WayneManion** [bambulab/BambuStudio#2085] opened 2023-07-20 15:05 UTC
### Bambu Studio Version

1.7.0 beta 2 (Fedora AppImage running on Arch)

### Where is the application from?

Bambu Lab github releases

### OS version

Arch

### Printer

Bambu P1P

### How to reproduce

Open a model that has a large opening on the inside. Use the space within that opening for other (smaller) models. BambuStudio throws warnings about the models not being far enough apart. 

Screenshot:
https://ibb.co/dtdsQWc

### Actual results

I don't know. If I see warnings I just abandon the nested models and print them later. 

### Expected results

Other slicers that I use with my other printers handle this scenario with no warnings or errors. Example: Cura 5.4.0 slicing for my Sovol SV06 Plus and Ender 3 Pro. 

### Project file & Debug log uploads

[NestedModels.zip](https://github.com/bambulab/BambuStudio/files/12110925/NestedModels.zip)
![BambuBug](https://github.com/bambulab/BambuStudio/assets/20778855/59078982-ea92-4f3b-be16-e5b50509b70e)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment] 2023-07-21 04:21
Hi @WayneManion 

thanks for reporting this issue

this warning is just used to mention there may has some objects too close, it can be skipped which won't affect the slicing
it uses the convex hull to do the detection which is not accurate for your nested cases
we had considered to use the real polygons to do the detection before(which will have an accurate result)
however, the performance will be bad

you can just go ahead for slicing and if there are print conflicts, there will be serious warnings
![image](https://github.com/bambulab/BambuStudio/assets/106916061/96ab1144-66b5-4e2f-a538-ed1c844f1a6a)

**Comment by lanewei120** [comment] 2024-01-16 06:08
as explained above, not a bug, close it

**Closed by lanewei120** 2024-01-16 06:08 UTC
Labels: bug
