### ISSUE TITLE
Layer number when printing

### ISSUE THREAD

**Issue by bigben4001** [bambulab/BambuStudio#805] opened 2022-12-11 00:26 UTC
I would like an option to see what layer the print is on as well as the total number of layers in the print so that users can have a better idea of how far along the print is as well as so that when multicolor prints are running, especially those with more striations than full color, it can be known where the color changes are easier since it can't be determined at the moment where the printer will change or stop changing.

**Comment by TheCableGuy99** [comment] 2022-12-11 13:45
Already posted and acknowledged it will be implemented in the next version

**Comment by TheCableGuy99** [comment] 2022-12-16 00:52
shame this wasn't implement as promised

**Comment by MadMax389** [comment] 2022-12-16 18:31
Might need the coming firmware update to be functional?

**Comment by spuiuk** [comment] 2023-01-25 09:28
I am running a multi colour print (no AMS) using pauses at layers. Seeing a current layer number/total layer numbers in place or along with the percentage completed would be very useful for me.

**Comment by spuiuk** [comment] 2023-01-25 09:41
I noticed that this feature has been added in  v1.4.2. Point #3
https://github.com/bambulab/BambuStudio/releases/

However it mentions X1/X1C and will rely on a future firmware update. I use a P1P and would like to see this feature included there too.

**Comment by spuiuk** [comment] 2023-01-25 13:51
duplicate of #604 ?

**Comment by timothyzalusky** [comment] 2023-02-07 18:20
[https://wiki.bambulab.com/en/x1/manual/X1-X1C-AMS-firmware-release-history

Added support for displaying the current layer number/total number of layers during printing](https://wiki.bambulab.com/en/x1/manual/X1-X1C-AMS-firmware-release-history#:~:text=of%20Bambu%20Studio-,Added%20support%20for%20displaying%20the%20current%20layer%20number/total%20number%20of%20layers%20during%20printing,-Added%20secondary%20confirmation)

Issue can be closed

**Closed** 2023-03-02 08:16 UTC
Labels: feature

**Comment by Hologos** [comment] 2023-03-12 17:01
@SaltWei: Can we get this feature on P1P as well please?

**Comment by StoneLiBambulab** [comment] 2023-03-13 00:38
Hi @Hologos ,
    The layer number can be displayed after the P1P printer firmware is upgraded. 

Thanks!
Stone Li

**Comment by Hologos** [comment] 2023-03-13 05:22
> Hi @Hologos ,
> 
>     The layer number can be displayed after the P1P printer firmware is upgraded. 
> 
> 
> 
> Thanks!
> 
> Stone Li

I'm on latest firmware but there is no layer number information. It works only for X1(C).

**Comment by Hologos** [comment] 2023-03-13 16:35
Here is a proof

<img width="1623" alt="image" src="https://user-images.githubusercontent.com/1620004/224766763-184b0631-847c-4267-a121-4b412ae47283.png">
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/1620004/224766808-952f8df6-2c02-4b33-ac0f-4e55e94c3dfa.png">
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/1620004/224766889-e3013946-7645-4726-9053-16463d0a8ec3.png">

**Comment by StoneLiBambulab** [comment] 2023-04-11 06:46
@Hologos , you can report a new one.

Thanks!
Stone Li
