### ISSUE TITLE
Cannot send jobs to the printer. After the update to 1.7.3.50 from today I cannot send jobs to the printer. The same issue with two X1C and one P1S. I have to send the several times, one after another to start printing. No errors displayed - Just does not print

### ISSUE THREAD

**Issue by kalpakchiev** [bambulab/BambuStudio#2295] opened 2023-08-14 15:08 UTC
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS 12.6.7

### Additional system information

Cannot send jobs to the printer. 

After the update to 1.7.3.50 from today I cannot send jobs to the printer. 
The same issue with all three printers I have -  two X1C and one P1S. 
I have to send the job several times, one after another to start printing. 
No errors displayed - Just does not print

### Printer

X1C and P1S

### How to reproduce

Print plate
Send

### Actual results

It looks like the job is loaded to the cloud, but then It is not downloaded to the printer and does not star printing

### Expected results

to print

### Project file & Debug log uploads

[15х20_v5_L.3mf.zip](https://github.com/bambulab/BambuStudio/files/12336438/15.20_v5_L.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by lanewei120** [comment] 2023-08-15 00:52
@kalpakchiev could you help to update the studio logs here?

you can refer to https://wiki.bambulab.com/en/x1/troubleshooting/bambu-studio-log for the howto

**Comment by kalpakchiev** [comment] 2023-08-15 08:20
Please find attached log file as per your request.

**Comment by walterwongbbl** [comment] 2023-08-15 12:21
@kalpakchiev 
Hi. Our network server has encountered some issues. We are trying to find out the reason

**Comment by lanewei120** [comment] 2023-08-19 06:28
the network server have been recovered before, close this issue

**Comment by kalpakchiev** [comment] 2023-08-20 07:55
What do you mean? The server on your side was down and because of that I wasn’t able to print the whole day? But at the same time all the services were indicated as “fully operational”!iPhone 12 ProOn 19 Aug 2023, at 9:28, Lane.Wei ***@***.***> wrote:﻿
the network server have been recovered before, close this issue

**Comment by kalpakchiev** [comment] 2023-08-20 07:56
Why was my case closed as completed? You never get back to me with a resolution? iPhone 12 ProOn 19 Aug 2023, at 9:28, Lane.Wei ***@***.***> wrote:﻿
Closed #2295 as completed.

**Comment by lanewei120** [comment] 2023-08-21 00:46
@kalpakchiev 
we are really sorry because we have a network server issue when you report your issue
so we thought it is the same issue caused by server

do you still have issues?
if yes, could you help to upload the logs from  /Users/user.name/Library/Application Support/BambuStudio/log?

let's reopen this issue

**Comment by kalpakchiev** [comment] 2023-08-21 09:23
Ok, but when I was having issues I checked the status of your service and it was stated that all services are operational. 

I believe this is the purpose of this site - to indicate problems with the print service.

**Comment by lanewei120** [comment] 2023-08-21 12:39
sure,  don't hesitate to contact us on github

So do you still have issues?
if yes, could you help to upload the logs from /Users/user.name/Library/Application Support/BambuStudio/log?

**Comment by walterwongbbl** [comment] 2023-10-13 02:52
Hi. @kalpakchiev 
I'm very sorry, have you recently experienced any printing issues?

**Comment by walterwongbbl** [comment] 2023-12-21 02:48
If you have any other issues, please create a new issue. The current conversation will be closed.

**Closed** 2023-12-21 02:47 UTC
Labels: bug
