### ISSUE TITLE
Build fails on Gentoo

### ISSUE THREAD

**Issue by desultory** [bambulab/BambuStudio#4301] opened 2024-06-16 19:38 UTC
### Bambu Studio Version

BambuStudio-01.09.02.57

### Where is the application from?

Bambu Lab github releases

### OS version

Gentoo 23.0

### Printer

Bambu A1 Mini

### How to reproduce

extract the release tarball,
```
cd BambuStudio/deps
mkdir build;cd build
cmake ../ -DDESTDIR="/home/<user>/tmp/BambuStudio-01.09.02.57/BambuStudio_dep" -DCMAKE_BUILD_TYPE=Release -DDEP_WX_GTK3=1
make -j32
```

### Actual results

Dependencies fail to build.

### Expected results

Dependencies build.

### Project file & Debug log uploads

https://0x0.st/Xc5C.txt

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by desultory** [comment] 2024-06-16 19:41
[build.log](https://github.com/user-attachments/files/15859653/build.log)

**Comment by JuergenKammer** [comment] 2024-06-20 16:41
That is a failure building OCCT, thus /maybe/ a duplicate of issue #4158. I posted my solution there. Try changing the OCCT.cmake as I described there. (Had the error on debian linux, would guess its a general one).

**Comment by desultory** [comment] 2024-06-20 17:30
Thanks for the info, I'll try that.

Could these deps somehow be submodules or something? or could there be an option for system libraries to be used?
I feel this process could be improved a bit.

**Comment by desultory** [comment] 2024-06-20 17:39
That patch works, thanks.

**Comment by lanewei120** [comment] 2024-06-26 01:08
thanks, @MackBambu will fix it soon

**Closed** 2024-08-26 00:04 UTC
Labels: bug
