### ISSUE TITLE
[Issue] Camera no longer works.

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#870] opened 2022-12-17 05:23 UTC
Upgraded to the latest version and camera won't play anymore. Keep getting "Stopped [-20000]!" error. However downgrading to the previous version, the camera works again.

**Comment by bani6809** [comment] 2022-12-17 09:08
I get this error also. Previous version of bambu studio works. Current version of bambu studio gives "Stopped [-20000]!" error.

**Comment by bani6809** [comment] 2022-12-17 09:10
Seems duplicate of #853

**Comment by LarryVand** [comment] 2022-12-17 14:23
What platform (Windows or Mac) and what version? On my windows 10 is working fine.

**Comment by SaltWei** [comment] 2023-03-02 07:38
Should be fixed in v1.5.0 public beta. Please have a check and let us known if still exist.
Thank you very much!

**Closed by SaltWei** 2023-03-02 07:38 UTC
Labels: duplicate
