### ISSUE TITLE
Error "unable to print filaments with big temperature difference"

### ISSUE THREAD

**Issue by kmeldner** [bambulab/BambuStudio#3742] opened 2024-03-19 18:44 UTC
### Bambu Studio Version

1.8.4.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu X1 Carbon

### How to reproduce

1) import model to print with 2 filaments
2) set filaments PA-CF and PLA
3) assign filaments to model parts

Error appears

### Actual results

Error appears and prevents user from slicing.
![image](https://github.com/bambulab/BambuStudio/assets/55151881/2d5e25bd-2118-460d-b94b-e7388183380c)

### Expected results

No error.
I want to print what I want without having to go through complicated workarounds.

For the time being I have found one not so complicated workaround which is to set print sequence to "by object" in which case error does not come up.
The other one is to define same type of filament with different print settings suitable for totally different type and physically feed what you want making AMS think it is suing something totally different.

### Project file & Debug log uploads

[mocowanie silnika 8NmY.zip](https://github.com/bambulab/BambuStudio/files/14654953/mocowanie.silnika.8NmY.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by kiler129** [comment] 2024-03-20 16:28
This is not a bug - the slicer is behaving exactly as it supposed to. You have multiple solids (that I'm guessing should be boolean-merged in your CAD):

![image](https://github.com/bambulab/BambuStudio/assets/1227834/cedd51c0-68cf-491d-9eb0-2014ad56e80c)

If you assign completely different filaments to different parts of the same model, these filaments cannot be too far in terms of temperature settings. If one filament is set to e.g. 250°C and another is 200°C you're going to clog the nozzle eventually, which the error is precisely informing you about. This is because during change the nozzle will be too cold to flush the higher temp filament fully.

You can print two dissimilar materials in "by object" mode, and it's not a workaround but a feature. However, these cannot be a single solid but two separate entities. In your case PA-CF and PLA must be separate solids anyway, as PA and PLA (similarly to PETG and PLA) do not bond.

**Comment by SaltWei** [comment] 2024-03-22 09:53
![image](https://github.com/bambulab/BambuStudio/assets/110660407/a162c228-5064-4e3b-bafd-af2592ab2335)

**Closed** 2024-03-22 09:54 UTC
Labels: bug, not-bug

**Comment by ZigZagT** [comment] 2024-11-05 06:48
I found the "temperature difference" check was introduced in commit https://github.com/SoftFever/OrcaSlicer/commit/96abc3209a0d4bb8f595cd8473e5796ffa6e3bd1

And it is configurable.

For me personally, I wanted to print TPU & ABS together. So I edited file `C:\Program Files\OrcaSlicer\resources\info\filament_info.json` and added both ABS and TPU to `"high_low_compatible_filament":`. 

This will allow ABS or TPU to be printed together with any filament. The clog risk is real, so use with caution!

**Comment by zbrozek** [comment] 2024-11-22 17:59
It's interesting that this is an explicit compatibility list and not a temperature delta check. Some flavors of PLA and ABS are quite-close in printing temperature and I think there is no risk of clogging. Further, I don't want my slicer to be nannying me anyway. I should be able to either disable this check or dismiss it and proceed anyway.

In fact, I find it kind of annoying that the slicer has any idea of what the polymer is at all. Why?

**Comment by dgutzler** [comment] 2025-05-22 06:01
how to allow this in bambu Studio. It saysthis can be enabled in prefereces

![Image](https://github.com/user-attachments/assets/eae84398-34fa-43e2-ab0d-761aec11f325)

**Comment by SaltWei** [comment] 2025-05-22 06:05
> how to allow this in bambu Studio. It saysthis can be enabled in prefereces
> 
> ![Image](https://github.com/user-attachments/assets/eae84398-34fa-43e2-ab0d-761aec11f325)

![Image](https://github.com/user-attachments/assets/7478bed2-905c-475b-a627-49ceecfe6b0a)

**Comment by dgutzler** [comment] 2025-05-22 06:08
found it. problem resolved
