### ISSUE TITLE
Color Bleed in slicer

### ISSUE THREAD

**Issue by Tedwell** [bambulab/BambuStudio#3681] opened 2024-03-06 17:53 UTC
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

OS: Windows 10

### Additional system information

Dell Alienware Area 51m R1  CPU: Intel core i9-9900k   Memory: 32gb  GPU: Nvidia 2080 

### Printer

X1 Carbon

### How to reproduce

Slice plate of color lettered model.

### Actual results

Layer 48 out of 50 has color errors outside of colored letters. Like a bleed in sliced lines. Occurs in printed model as well.  Seems to happen with coloring of neighboring characters and not where the bleed is. So far it has only happened to this particular model. Other prints have come out clean.
[X1C Color Error in slicer.docx](https://github.com/bambulab/BambuStudio/files/14513414/X1C.Color.Error.in.slicer.docx)

### Expected results

clean colored letters

### Project file & Debug log uploads

[Test tube holder names v9.zip](https://github.com/bambulab/BambuStudio/files/14513718/Test.tube.holder.names.v9.zip)
[debug_Mon_Mar_04_10_09_45_19804.log.zip](https://github.com/bambulab/BambuStudio/files/14513721/debug_Mon_Mar_04_10_09_45_19804.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Tedwell** [comment] 2024-03-06 18:46
Nvidia GeForce RTX 2080

**Comment by Tedwell** [comment] 2024-03-06 19:43
I increased the size of the model to 100.01% with no bleed. Yay!!! Now off to print to see if it prints correctly as well. Still want to know why it bled in the first place. Tolerances are crucial to this model.

**Comment by Tedwell** [comment] 2024-03-06 20:49
It printed fine. No bleed. I redesigned characters in Fusion 360. Loaded it into Bambu Studio. Colored the characters in Bambu Studio with fill. Same as before. Still bleeds. Increased scale to 100.01% and no bleed. Did I just find a glitch or is something else going on.

Thanks

**Comment by Tedwell** [comment] 2024-03-07 20:08
![20240307_120516](https://github.com/bambulab/BambuStudio/assets/87158936/4b9a135a-a9cf-4a08-ba6f-49ab4624c83b)
Top pic at layer 48/50. Middle pic at layer 50/50. Bottom pic is a good print by increasing scale to 100.01%.

**Comment by Tedwell** [comment] 2024-03-10 17:04
Anyone here to comment on this issue?

**Comment by zhimin-zeng-bambulab** [comment] 2024-03-11 02:05
Thanks for reporting this issue, it is a BUG and we are investigating the cause.

**Comment by MonsterMaxx** [comment] 2024-03-12 18:26
I have something that's tan w/ red lettering.  Can clearly see the bleed.
![PXL_20240304_163324575](https://github.com/bambulab/BambuStudio/assets/88036569/2e863466-f60a-4673-9969-d6e2d6b01902)

**Comment by Tedwell** [comment] 2024-03-13 01:06
> I have something that's tan w/ red lettering. Can clearly see the bleed. I have not yet printed this again so I don't know what the solution would be. ![PXL_20240304_163324575](https://private-user-images.githubusercontent.com/88036569/312196161-2e863466-f60a-4673-9969-d6e2d6b01902.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTE2MjksIm5iZiI6MTcxMDI5MTMyOSwicGF0aCI6Ii84ODAzNjU2OS8zMTIxOTYxNjEtMmU4NjM0NjYtZjYwYS00NjczLTk5NjktZDZlMmQ2YjAxOTAyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAwNTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NDNlZGM5MDUzMTZiOWRiZDg4MDZhYjRjN2EwMTI3MzBlYTAzOTQ5OTc0NWY0YTQ4NmZjMzE1ZjJjODU4YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZXp53WDz__7wCLGURGQ2YahI-mdY89WlMlRGlgrHYjs)

Does it look the same in Bambu Studio?

**Comment by zhimin-zeng-bambulab** [comment] 2024-03-13 01:06
@MonsterMaxx  Could you share your 3mf file?

**Comment by MonsterMaxx** [comment] 2024-03-13 01:09
> @MonsterMaxx Could you share your 3mf file?

no I can't share, sorry, the stls are confidential.

**Comment by MonsterMaxx** [comment] 2024-03-13 01:13
![image](https://github.com/bambulab/BambuStudio/assets/88036569/abf90381-0088-462f-96b0-a52c11ad88a8)
in the slicer it looks clean, no bleed, but as you can see by the actual part it's pretty bad.

Can I get control over 'retraction'??  I think a little more retraction might solve the problem.

**Comment by zhimin-zeng-bambulab** [comment] 2024-03-13 01:17
![image](https://github.com/bambulab/BambuStudio/assets/120697589/92cf624c-01d0-407a-92e7-a66419d8408e)
You can try to increase this value.

**Comment by Tedwell** [comment] 2024-03-13 19:54
> Thanks for reporting this issue, it is a BUG and we are investigating the cause.

Thank you for this information. Please let us know the outcome.

**Comment by zhimin-zeng-bambulab** [comment] 2024-03-14 01:02
> Thank you for this information. Please let us know the outcome.
we will fix it in the next version

**Comment by EricDimitri** [comment] 2024-03-17 01:18
> > Thank you for this information. Please let us know the outcome.
> 
> we will fix it in the next version

When will next version be released? Is there an ETA?

Thank you!!

**Comment by zhimin-zeng-bambulab** [comment] 2024-03-27 01:11
it has been fixed in v 01.09.00.06

**Closed by zhimin-zeng-bambulab** 2024-03-27 01:11 UTC
Labels: bug

**Comment by Tedwell** [comment] 2024-03-31 01:10
> I have something that's tan w/ red lettering. Can clearly see the bleed. I have not yet printed this again so I don't know what the solution would be. ![PXL_20240304_163324575](https://private-user-images.githubusercontent.com/88036569/312196161-2e863466-f60a-4673-9969-d6e2d6b01902.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NDc2MjQsIm5iZiI6MTcxMTg0NzMyNCwicGF0aCI6Ii84ODAzNjU2OS8zMTIxOTYxNjEtMmU4NjM0NjYtZjYwYS00NjczLTk5NjktZDZlMmQ2YjAxOTAyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAxMDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiOWFmMTA4NTk1ZWM2Zjk2MDRmYWRmNDA3OWYxNTMxM2MyYjU0NGI2NjI2NTUwYzcyMDI5MTA0MDMwYTExZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AMbk4pftwd1SK36JEzH5qVXHliGBJNLpLnAtBipN9VA)

Could this be caused by "Reduce Waste during Filament Change" setting? https://wiki.bambulab.com/en/software/bambu-studio/reduce-wasting-during-filament-change

**Comment by zhimin-zeng-bambulab** [comment] 2024-04-02 06:08
> Could this be caused by "Reduce Waste during Filament Change" setting? https://wiki.bambulab.com/en/software/bambu-studio/reduce-wasting-during-filament-change

Maybe, since there is no 3mf file, I don't know how your parameter settings. 
You could try to increase the flushing volume, or don't choose "flush into object's infill".
