### ISSUE TITLE
View resets with every change when re-sliced.

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#111] opened 2022-08-09 20:30 UTC
#20  should also be that way with the current view staying the same with every slice, that way you can zoom in on a spot that needs some adjustment and instantly see how your changes affect the model.  This is standard behavior in Cura.

**Comment by YifanWuBambu** [comment] 2022-08-10 02:35
@randyre The issue is fixed in v1.1.1.1.

**Closed by YifanWuBambu** 2022-08-10 02:35 UTC
