### ISSUE TITLE
X1C First layer Nozzle temperature not working

### ISSUE THREAD

**Issue by verityworks** [bambulab/BambuStudio#1381] opened 2023-03-02 16:58 UTC
When Selecting a filament, setting the first layer temperature does not appear to have any effect while printing on the X1C.
It takes the Other Layer Temperature for the whole print, except the L shape calibration line.
(Similar to bug 1044 on the P1P)

**To Reproduce**
1. Go to Filament Settings
2. Change First Layer Nozzle Temperature to something other than the Other Layer Temperature
3. Slice a model, and look at the preview.
4. Select "Temperature" in the Color Scheme preview, to see what Temperature the GCode is supposed to be using

Expected to have the whole 1st layer set to this filament temperature

This bug appears to be fixed for the P1P machine, but I dont know how to get the GCode fix into the X1C settings.

 - OS: [Windows]
 - Version [1.4.x] AND [1.5.x] public beta

**Comment by SaltWei** [comment] 2023-03-03 01:27
![image](https://user-images.githubusercontent.com/110660407/222608317-c2a384b8-8319-4817-ba4a-c47b71f9f5d3.png)
Seem to be OK for X1C

**Comment by SaltWei** [comment] 2023-03-03 01:28
The calibration line should be printed by other layer temperature to make the PA calibration match with most part of model

**Comment by verityworks** [comment] 2023-03-03 08:58
Diving deeper, it seems ok with just a simple STL that doesnt require support.
I;m trying to print PETG with a PLA interface layer as support, and then I get this as the first, and all other layers.
![image](https://user-images.githubusercontent.com/123553299/222676726-8f08dd00-39b2-42da-82d4-a492b1bae6e4.png)

**Comment by SaltWei** [comment] 2023-03-07 07:01
We can reproduce this issue now.
![image](https://user-images.githubusercontent.com/110660407/223347746-14f98218-6e8c-4efe-ab68-571f25330ca3.png)
This issue is caused by change filament gcode, and after switching filament in first layer, the temperature is always using other layer temperature without judging whether is in first layer or not.

We will fix it, thank you very much!

**Comment by zhimin-zeng-bambulab** [comment] 2023-04-18 01:43
It fixed in v1.6 released on github.

**Closed by zhimin-zeng-bambulab** 2023-04-18 01:43 UTC
Labels: bug

**Comment by joshthehappy** [comment] 2024-07-01 18:41
I'm seeing something like this right now, I set a first layer temp and the printer or the slicer is ignoring it. Weird thing is it used to work just check the box and good to go.
