### ISSUE TITLE
Tree support trough model.

### ISSUE THREAD

**Issue by Kwintyy** [bambulab/BambuStudio#1087] opened 2023-01-16 14:51 UTC
**Describe the bug**
Tree support starts from build plate and then goes trough model without touching it. The support structure from the build plate to the model will be not used when the support structure rests on the model its self. See the pictures with and without outlines.

**3mf File for This Bug**
see included zip file, tree support.3mf
[tree support.3mf.zip](https://github.com/bambulab/BambuStudio/files/10426778/tree.support.3mf.zip)

**To Reproduce**
Slice a internally overhanging bowl with tree support on auto

**Expected behavior**
Support trees starting from inside the model from one point. And then move outwards.

**Screenshots**
<img width="667" alt="Scherm­afbeelding 2023-01-16 om 15 41 52" src="https://user-images.githubusercontent.com/55090000/212705520-9f3c67ee-0bb6-4221-9482-a2916b658ca3.png">
<img width="800" alt="Scherm­afbeelding 2023-01-16 om 15 41 42" src="https://user-images.githubusercontent.com/55090000/212705549-f33aedbf-9729-4cfa-9a80-25466da4707f.png">
<img width="625" alt="Scherm­afbeelding 2023-01-16 om 15 41 08" src="https://user-images.githubusercontent.com/55090000/212705582-c8a1a983-10b4-4ea4-a021-28c03b05fa22.png">
<img width="714" alt="Scherm­afbeelding 2023-01-16 om 15 40 56" src="https://user-images.githubusercontent.com/55090000/212705609-4df8cf23-b9e9-4ccd-8473-1fc0594db071.png">

**Desktop (please complete the following information):**
 - OS: [macOS 13.0.1]
 - Version 1.4.1.52

**Comment by SaltWei** [comment] 2023-01-17 08:41
@tangketan @MusangKingBambulab Please help to check this issue

**Comment by MusangKingBambulab** [comment] 2023-01-18 03:49
Hi @Kwintyy, I have checked the tree support generation under this situation, and from my personal view, there is no problem in tree support generation with your provided 3mf. Technically, the bowl model contains the avoidance space of internal "trees" as its subspace so that some tree supports hardly reach outside and look like to be cut by the bowl. Hence, it seems impossible to realize your expected behavior, since trees can not be grown over the overhang area along the Z-direction.

**Comment by SaltWei** [comment] 2023-03-02 01:36
Please share more information included 3MF file.
By the way, v1.5.0 Public beta has been released. Close this issue at the moment.
Reopen this issue if need to be discussed further

**Closed by SaltWei** 2023-03-02 01:36 UTC
Labels: bug
