### ISSUE TITLE
[BUG] Useless Block Support Enforcers still not working on latest BambuStudio

### ISSUE THREAD

**Issue by bolsoncerrado** [bambulab/BambuStudio#2733] opened 2023-10-15 10:29 UTC
### Bambu Studio Version

1.7.7.8.9

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS Ventura

### Additional system information

M1Ultra

### Printer

X1C, P1P

### How to reproduce

1. Create a job
2. Enforce support blockers like in the pics
3. Preview.

### Actual results

4. Supports are not blocked

### Expected results

Supports....blocked?

### Project file & Debug log uploads

<img width="536" alt="Captura de pantalla 2023-10-15 a las 11 51 18" src="https://github.com/bambulab/BambuStudio/assets/10992914/1dd7a017-0de9-465e-b0bc-ca34a274a5f2">
<img width="570" alt="Captura de pantalla 2023-10-15 a las 11 51 11" src="https://github.com/bambulab/BambuStudio/assets/10992914/c47af7cc-64cf-4c47-bbd5-07e65a2250c4">
<img width="404" alt="Captura de pantalla 2023-10-15 a las 12 28 35" src="https://github.com/bambulab/BambuStudio/assets/10992914/6f762952-b922-4ecf-978d-3dcff7c15587">
<img width="535" alt="Captura de pantalla 2023-10-15 a las 12 28 49" src="https://github.com/bambulab/BambuStudio/assets/10992914/f83f5bae-61d9-4464-a63c-b4eda3f34c61">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by bolsoncerrado** [comment] 2023-10-15 10:30
Might be related to July's issue: https://github.com/bambulab/BambuStudio/issues/2019

**Comment by tangketan** [comment] 2023-10-24 04:05
3mf file please.

**Comment by bolsoncerrado** [comment] 2023-10-24 06:27
@tangketan sure, is there a way to share the file "privately"?

**Comment by tangketan** [comment] 2023-10-24 12:31
@bolsoncerrado You may email me: arthur.tang at bambulab.com

**Comment by tangketan** [comment] 2024-03-29 13:16
@bolsoncerrado Sorry for the late reply. Your 3mf has both enforcers (painted supports) and blockers, and enforcers have higher priority.

**Comment by tangketan** [comment] 2024-03-29 13:18
I'm closing this issue since it's not a bug. But feel free to re-open it if you'd like more discussion.

**Closed by tangketan** 2024-03-29 13:18 UTC
Labels: bug, backend
