### ISSUE TITLE
Save Project does not work correctly for a new project

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1777] opened 2023-05-08 18:21 UTC
**Describe the bug**

When I create a new project, import an STL file and then use `<ctrl>s` to save nothing happens.
There is no warning or error.
I then open the file menu and Save Project is disabled.

![image](https://user-images.githubusercontent.com/5090005/236899860-6ec33644-49f5-4e2a-97dc-0c70d4f11567.png)

This is not standard behavior. The standard behavior that applications have been using for more than two decades is to have Save invoke Save As when the current document is new and has not been saved. In addition, the Save As dialog should have a default name filled in, which is commonly something like "Untitled 1".

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
1. Create new project
2. try to save using `<ctrl>s` or File/Save

**Expected behavior**

The "Save As" dialog should appear, with a default name filled in, allowing the user to optionally give the project a name of their choosing and then save it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows]
 - Version 1.6.2.4

**Comment by julie777** [comment] 2023-05-08 18:29
It turns out that save does work for a new project, just not always correctly.
I was writing this bug because I discovered it while writing a different bug report. The symptoms that I saw and reported above were confusing because `<ctrl>s` had saved the file, but without displaying a dialog for me to enter a file name or choose a location.

**Works**

If I create a new project and immediately save it, the Save as dialog opens with the file named Untitled.3mf. This is working as I would expect.

**Bug**

However, if I create a new project, import an STL file and then use `<ctrl>s` it does not open the save as dialog. Instead it silently saves the new project using the name of the STL file, which is not standard, not what one would expect, and could possibly cause accidental overwrite of an existing project file.

**Comment by bambu123** [comment] 2023-05-10 10:14
I can't reproduce it. 
Maybe you are using an opened project instead of creating a new one before importing an STL file.

**Comment by bambu123** [comment] 2023-05-22 05:44
@julie777 
Is it responsible recently?

**Comment by bambu123** [comment] 2023-07-11 07:24
Close as fixed in the 1.7 beta version.

**Closed by bambu123** 2023-07-11 07:24 UTC
Labels: bug
