### ISSUE TITLE
Unable to change fan speed settings in Bambu Studio

### ISSUE THREAD

**Issue by saltylemonbreeze** [bambulab/BambuStudio#4082] opened 2024-05-16 05:48 UTC
### Bambu Studio Version

1.91.66

### Where is the application from?

Built from source by yourself or others

### OS version

Fedora 40

### Printer

Bambu A1 mini

### How to reproduce

In the prepare window, go to filament settings - cooling. Try to change the fan speed settings on this window.

### Actual results

Not possible to change the fan speed.

Also when I go back to the temperature settings window, now I can't change the temperature any more. Temperature settings only work again after re-starting Bambu studio.

### Expected results

Fan speed settings should be able to choose/edit to change the fan speed.

### Project file & Debug log uploads

[log files.zip](https://github.com/bambulab/BambuStudio/files/15330185/log.files.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by mzient** [comment] 2024-05-17 10:28
Duplicate of #3796 ?

**Comment by kbokh** [comment] 2024-05-17 19:33
The same Arch (EndevourOS)
Mostly all settings in the tab Cooling are not changeable. Checkboxes sometimes can be changed, sometimes - not.

**Comment by mcgiver0510** [comment] 2024-05-18 00:58
the same Issue with Arch Linux. Mostly all settings in the tab Filament Settings and Cooling are not changeable.

**Comment by bambu123** [comment] 2024-06-12 04:19
Fixed in version 1.9.2.

**Closed by bambu123** 2024-06-12 04:19 UTC
Labels: bug
