### ISSUE TITLE
AUX fan not turning on after first layer in 01.02.00.99

### ISSUE THREAD

**Issue by adamhf** [bambulab/BambuStudio#270] opened 2022-09-14 00:38 UTC
When printing PLA in v1.1.1.1 the AUX fan would be enabled after printing and validating the first layer.  In 01.02.00.99 the AUX fan is enabled during the first layer validation, but is disabled after it has been completed and is not re-enabled during the print.

**Comment by SaltWei** [comment] 2022-09-15 10:22
Can't reproduce, please share the 3MF or check whether the filament preset you used disables the AUX fan.
![image](https://user-images.githubusercontent.com/110660407/190380087-e8d3e5b1-a6c3-4f6b-ae4d-f7592f06060d.png)

**Comment by adamhf** [comment] 2022-09-15 17:14
Hey @SaltWei,

I appreciate you getting back to me.

I have confirmed that 

the Aux part cooling fan is enabled in the filament profile, its the default Bambu Matte PLA profile.

![image](https://user-images.githubusercontent.com/581833/190468267-e15ab827-1ba4-4e58-a434-e5678656e96a.png)

Here is a 3MF exported from 01.02.00.99 running on Windows 11

[aux-fan-test.zip](https://github.com/bambulab/BambuStudio/files/9577507/aux-fan-test.zip)

**Comment by adamhf** [comment] 2022-09-15 17:35
Here is the same model sliced in 1.1.1.1 with the AUX fan working after layer 1.

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/581833/190472333-cab20e1d-afc7-41ef-bcab-3599aa4d43ec.png">

[aux-fan-test-working.3mf.zip](https://github.com/bambulab/BambuStudio/files/9577684/aux-fan-test-working.3mf.zip)

**Comment by adamhf** [comment] 2022-09-15 21:07
I did some analysis with mowcius on the Discord and it looks like the ordering of the `M976 S1 P1` command in the gcode has changed, presumably in [this MR](https://github.com/bambulab/BambuStudio/commit/e7c977f86b1a727541f20eeec18699abef46c2ce).

Interestingly if I disable the First Layer Inspection the AUX fan spin up as expected

**Comment by SaltWei** [comment] 2022-09-16 04:07
Yes. The aux fan is opened in gcode by M976 P2 S178.
I have comfirmed with printer firmware guys, and this is bug of printer firmware and will be fixed soon.
Thank you very much for this finding!

**Comment by adamhf** [comment] 2022-09-16 15:39
Not a problem :) thanks for the update.

**Closed** 2022-10-12 06:12 UTC
Labels: bug, Printer
