### ISSUE TITLE
I dont have the Colour Symbol anymore

### ISSUE THREAD

**Issue by ONLYTM** [bambulab/BambuStudio#3589] opened 2024-02-14 18:26 UTC
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

11

### Printer

P1S

### How to reproduce

cant use the Colour Option on BambuStudio

### Actual results

nothing

### Expected results

I need the Symbol to print in more than one colour

### Project file & Debug log uploads

![Bild_2024-02-14_192606377](https://github.com/bambulab/BambuStudio/assets/160057631/344a58af-ba43-408b-9ee4-6169a6605d13)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Xboxer** [comment] 2024-02-14 22:09
You need to add a second Filament to enable the Colour Icon

**Comment by ONLYTM** [comment] 2024-02-15 07:31
Thank you 🙏🏻Gesendet mit der mobilen Mail AppAm 14.02.24 um 23:10 schrieb Xboxer
                
            
            
                
                    Von: "Xboxer" ***@***.***>Datum: 14. Februar 2024An: "bambulab/BambuStudio" ***@***.***>Cc: "Author" ***@***.***>,"ONLYTM" ***@***.***>Betreff: Re: [bambulab/BambuStudio] I dont have the Colour Symbol anymore (Issue #3589)
                
                
You need to add a second Filament to enable the Colour Icon

**Comment by lanewei120** [comment] 2024-02-18 01:43
you can also find some guide on our wiki

https://wiki.bambulab.com/en/software/bambu-studio/color-painting-tool
https://wiki.bambulab.com/en/x1/manual/multi-color-printing

**Comment by lanewei120** [comment] 2024-02-18 01:43
as it is not a bug, close it currently

**Closed by lanewei120** 2024-02-18 01:43 UTC
Labels: bug
