### ISSUE TITLE
Linux Support!

### ISSUE THREAD

**Issue by iplayfast** [bambulab/BambuStudio#758] opened 2022-12-03 18:59 UTC
The software is based off of the PrusaSlicer which supports Linux. 
There are a fair number of users that use desktop Linux specifically for slicing and 3d printing tasks. 
You should support it in your releases.

**Comment by deftdawg** [comment] 2022-12-04 19:11
Duplicate of #12

**Comment by lanewei120** [comment] 2023-03-02 09:48
first linux version on ubuntu has been released, 
and now we can build linux version by ourselves following the guide https://github.com/bambulab/BambuStudio/wiki/Linux-Compile-Guide

**Closed by lanewei120** 2023-03-02 09:48 UTC
Labels: feature
