### ISSUE TITLE
Wrong number of layers on MacOS version

### ISSUE THREAD

**Issue by mctazman** [bambulab/BambuStudio#1967] opened 2023-06-28 11:58 UTC
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS 13.4.1

### Additional system information

![Scherm­afbeelding 2023-06-28 om 13 54 51](https://github.com/bambulab/BambuStudio/assets/113347370/6332d5cf-7ef0-4977-bd59-eec4c933f8b0)

### Printer

X1carbon/AMS

### How to reproduce

[tail.3mf.zip](https://github.com/bambulab/BambuStudio/files/11893716/tail.3mf.zip)
Slice the 3mf file on MacOS and Windows

### Actual results

![Scherm­afbeelding 2023-06-28 om 13 50 05](https://github.com/bambulab/BambuStudio/assets/113347370/be0031ae-e645-47b1-9719-49c28d8cc309)
As you can see in this screenshot, the left (MacOS version) shows the wrong number of layers for the print, while the right (WIndows 11 VM, Windows version) shows the correct number of layers

### Expected results

The correct amount of layers post-slice on Mac and Windows.

### Project file & Debug log uploads

[tail.3mf.zip](https://github.com/bambulab/BambuStudio/files/11893746/tail.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by lanewei120** [comment] 2023-06-29 12:23
@mctazman 
Hello, thanks for reporting this issue

as we don't have the same mac version with you,
we have tried the same 3mf with 1.6.2.4 on following mac versions:
Mac 13.2.1
Mac 12.2.1
both of them can not reproduce this issue

it seems the support's height is not aligned with the normal print
so the support's layers will be treated as different layers
to confirm this issue
please turn off the support, to check the layer count again

we doubt it is related with computing precision
does other model have this issue?

**Comment by SaltWei** [comment] 2023-06-29 12:28
> we doubt it is related with computing precision

Yes, we met other issues on specific macos system which is caused by float computing precision. Finally wrong cooling speed was applied.

We doubt this issue is caused by same reason as well but still can't reproduced at the moment.

**Comment by mctazman** [comment] 2023-06-30 07:27
@lanewei120 The fault doesn't happen on all models. See, for instance, attached 3mf file. There's no error in layer height when slicing.
[brooms.3mf.zip](https://github.com/bambulab/BambuStudio/files/11914011/brooms.3mf.zip)
It could be an Apple Silicon issue, but I doubt it, as issue #1969 also displays weird layer number behaviour, but then on a WIndows machine.

**Comment by lanewei120** [comment] 2023-06-30 11:12
> @lanewei120 The fault doesn't happen on all models. See, for instance, attached 3mf file. There's no error in layer height when slicing. [brooms.3mf.zip](https://github.com/bambulab/BambuStudio/files/11914011/brooms.3mf.zip) It could be an Apple Silicon issue, but I doubt it, as issue #1969 also displays weird layer number behaviour, but then on a WIndows machine.

very strange, still can not reproduce issue 1969 also
we will try to find more machines to have a try

for this issue, if turn off support ,is this issue still there?

**Comment by mctazman** [comment] 2023-06-30 11:20
I've done 3 tests:

support off / prime tower on -> correct number of layers (607)
support on / prime tower off -> incorrect number of layers (625)
support off / prime tower off -> correct number of layers (607)
![support off-prime tower off](https://github.com/bambulab/BambuStudio/assets/113347370/1ed27852-5f4b-4916-a234-5ae4adfe78ed)
![support off-prime tower on](https://github.com/bambulab/BambuStudio/assets/113347370/ec8163d0-f67d-4fed-9ac6-17873c01ebf0)
![support on-prime tower off](https://github.com/bambulab/BambuStudio/assets/113347370/5d4d7039-9e07-4203-ab45-8757ac47df3d)

So, prime tower's a factor as well, apparently

**Comment by SaltWei** [comment] 2023-06-30 11:26
> So, prime tower's a factor as well, apparently

This is normal. Primer tower only works when all extrusion(objects and support) has same layer height.
When primer tower is disabled, the support can generate independent layer height with model, so the layer counter is larger.
Layer height of support is aligned with object when primer tower is enabled. So the later number may be lower.

**Comment by mctazman** [comment] 2023-06-30 11:29
> > So, prime tower's a factor as well, apparently
> 
> This is normal. Primer tower only works when all extrusion(objects and support) has same layer height. When primer tower is disabled, the support can generate independent layer height with model, so the layer counter is larger. Layer height of support is aligned with object when primer tower is enabled. So the layer number is lower.

I understand, but my point is that both turned on, the layer count goes from 607 (both off) to 627 (only supports) to 914 (both on). So the prime tower has a significant impact, whilst it's obviously not adding layers, just extruded plastic.

**Comment by SaltWei** [comment] 2023-06-30 11:33
> 914 (both on)

Can not reproduce at the moment. We are keeping trying. My version is 1.6.2.4, windows 10 system.
![image](https://github.com/bambulab/BambuStudio/assets/110660407/3e9708b3-193b-477c-9190-7bbe270969b0)

**Comment by Hologos** [comment] 2023-07-03 17:53
> > 914 (both on)
> 
> 
> 
> Can not reproduce at the moment. We are keeping trying. My version is 1.6.2.4, windows 10 system.
> 
> ![image](https://github.com/bambulab/BambuStudio/assets/110660407/3e9708b3-193b-477c-9190-7bbe270969b0)
> 
> 

Hello, guys. From the image, OP is using 0.08mm preset but from the name, it's his own. @SaltWei is using stock 0.08mm preset. You should use his profile from included 3mf file.

**Comment by BambooBugFixer** [comment] 2023-07-13 01:52
I used a Mac with Ventura 13.4.1 and a bamboo studio with a version of 1.6.2.4. I sliced your model with the support and prime tower on and the number of layers is right.  
![image](https://github.com/bambulab/BambuStudio/assets/139194735/27764523-c35a-4f78-91b9-eb08247b714a)

Only when I turn the support on and the prime tower off, there are a little bit more layers. But this is normal.
![img_v2_cf778494-8687-4d91-a963-b5238c8a78dg](https://github.com/bambulab/BambuStudio/assets/139194735/cd6d79ca-c2cf-4ef9-b462-3f8f88bc73ad)

**Comment by mctazman** [comment] 2023-08-18 08:34
I’ll have to try later. Am currently printing another project. Will check later today.

Op 18 aug. 2023 om 10:38 heeft SaltWei ***@***.***> het volgende geschreven:

﻿

@mctazman<https://github.com/mctazman> Hello. Does this issue still exist on your environment with 1.7.4 version?

**Comment by mctazman** [comment] 2023-08-20 11:14
OK, tad later than I wanted to, but finally got to test the layer-issue. I gave it the worst possible case I could quickly think up & seemingly it works perfectly:
![Scherm­afbeelding 2023-08-20 om 12 11 42](https://github.com/bambulab/BambuStudio/assets/113347370/580aba16-c30a-4bec-829c-aa8bf1caf13e)
![Scherm­afbeelding 2023-08-20 om 13 11 46](https://github.com/bambulab/BambuStudio/assets/113347370/990aa667-eb07-473a-9f9e-5f56b8d4499e)
If wanted, I can upload the 3mf file, but it seems that the issue's solved.

**Comment by SaltWei** [comment] 2023-08-21 00:55
> but it seems that the issue's solved.

Thank you very much. So we can close this issue now.
Please reopen if could reproduce again.

**Closed by SaltWei** 2023-08-21 00:55 UTC
Labels: bug
