### ISSUE TITLE
Studio doesnt use correct color/slot when painting

### ISSUE THREAD

**Issue by Edzi11** [bambulab/BambuStudio#2275] opened 2023-08-11 21:05 UTC
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

1. Open 3mf
2. Slice
3. top model has been painted with a yellow bandana while the bottom has a brown bandana
4. top model doesnt use the color that was used with slot one even if you change the color to any color as long as its from slot one / color one after slicing the model wont reflect that. 
![EaseUS_2023_08_11_13_59_39](https://github.com/bambulab/BambuStudio/assets/123626106/a0a79fe7-4cb1-4ab5-973c-5c2fc4c38a8b)

### Actual results

top model with yellow bandana doesnt slice correctly / slot 1 color isnt being used

brown color doesnt have any issue being sliced 
![EaseUS_2023_08_11_13_54_39](https://github.com/bambulab/BambuStudio/assets/123626106/e552f790-724d-4d2c-873f-4c24a6ff9fcf)

### Expected results

top model should be using the color that was used to paint it (yellow) in slot 1 

### Project file & Debug log uploads

[nameplate example.zip](https://github.com/bambulab/BambuStudio/files/12325131/nameplate.example.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by hcona** [comment] 2023-08-12 15:49
I am having similar issues. When coloring one part of a model that is supposed to be extruded through the entire piece, only one side gets colored and the other side does not - I have to fill on the other side.  When slicing, it shows that the color is only a couple layers deep and does not go all the way through.  

Additionally, when I have more than one model to color, it merges the two items so I cannot color them separately.  I have to go to the object window and select each part separately, each color separately, in order to color the second item.

**Comment by zhimin-zeng-bambulab** [comment] 2023-08-18 07:32
When there are multiple parts of different colors under an Object, and they overlap each other, the material used for the overlapping part depends on the position of the part in the object list. The lower the position, the higher the printing priority.

So, if you want the correct color printing order, you can drag "Component 8" before the yellow Parts, the drag and drop function has been released in version v1.7.4, you can have a try.

![image](https://github.com/bambulab/BambuStudio/assets/120697589/c8d771c7-d405-4320-b9da-5eb61e7eed6d)

**Comment by hcona** [comment] 2023-08-18 15:58
Thank you for the suggestion.  I was not aware of the drag-and-drop feature, but I have been able to manipulate the colors through the component boxes.

The specific issue I am having is this:  I am trying to test out a couple different prints, so I put one version in a file, colorize it, then import a different version of the file.  When I try to colorize it, it merges with the existing one even though I have selected only the new part, so I have to edit the colors in the component window.  



![image](https://github.com/bambulab/BambuStudio/assets/94251770/20af8b74-0826-4b72-90f9-3f432f32daf2)

![image](https://github.com/bambulab/BambuStudio/assets/94251770/4cdd7723-4ff4-47bf-9ca7-ddd141da962d)

**Comment by Edzi11** [comment] 2023-08-18 16:24
> @Edzi11 When there are multiple parts of different colors under an Object, and they overlap each other, the material used for the overlapping part depends on the position of the part in the object list. The lower the position, the higher the printing priority.
> 
> So, if you want the correct color printing order, you can drag "Component 8" before the yellow Parts, the drag and drop function has been released in version v1.7.4, you can have a try.
> 
> ![image](https://user-images.githubusercontent.com/120697589/261533625-c8d771c7-d405-4320-b9da-5eb61e7eed6d.png)

Thank you, I'll give this a try and see if it helps!

**Comment by zhimin-zeng-bambulab** [comment] 2023-08-30 03:33
@Edzi11   Is this problem been resolved?

**Comment by Edzi11** [comment] 2023-08-30 03:50
> @Edzi11 Is this problem been resolved?

Yes, your Instructions worked thanks!

**Comment by hcona** [comment] 2023-08-30 05:20
Not mine.  When I have more than one model on a plate at a time, they
overlap each other and I cannot color them using the fill or the assembly
feature.  I have to go into each object, select each section, then
selecting the colors.

**Comment by zhimin-zeng-bambulab** [comment] 2023-08-30 06:08
@hcona  Could you share your 3mf file? And describe your expected results.

**Comment by zhimin-zeng-bambulab** [comment] 2023-08-31 01:46
@hcona  You can compress the 3mf file into a zip file and upload it.

**Comment by zhimin-zeng-bambulab** [comment] 2023-08-31 01:47
You can also tell me the BUG phenomenon you encountered and the expected result.

**Comment by hcona** [comment] 2023-08-31 03:49
[Problem Test.zip](https://github.com/bambulab/BambuStudio/files/12481992/Problem.Test.zip)
Here is the file.  

I am expecting to be able to place two different models on the same plate.  I expect to be able to select each model individually and color them separately.  Currently, when I have two models and I try to color them, they are stacked on top of each other and I cannot color them using the tools available.  They must be colored using the object window that lists all the parts.  I end up having to select each part, use the drop-down menu to select the color, then repeat this for every part on the model.

I have tried coloring one model, then importing the next model, but they get merged and the second model cannot be colored in the same manner.

Thanks for your help.

**Comment by zhimin-zeng-bambulab** [comment] 2023-09-01 11:17
![image](https://github.com/bambulab/BambuStudio/assets/120697589/2f9f2da4-50a6-406d-a62d-018b431bff10)
@hcona  Even if they are stacked on top of each other, they can be colored, and you can choose different tools according to your needs. Could you have a try?

**Comment by hcona** [comment] 2023-09-01 16:20
Thank you, I have tried that.  The problem is that they are not really stacked on top of each other, they are merged, so I cannot separate the part to color.  I redid the example so you can better see the problem.  Let me know if this is a better example.  When you go to the assembly coloring, they are merged so that it is very difficult to choose the part I want to color.
[Problem Test (2).zip](https://github.com/bambulab/BambuStudio/files/12499842/Problem.Test.2.zip)

**Comment by zhimin-zeng-bambulab** [comment] 2023-09-05 10:53
@hcona 
I may understand what you mean. You want to select a part separately instead of the entire object for coloring. But currently we do not support selecting a part separately for coloring. You can create a new issue to record your request.

**Comment by hcona** [comment] 2023-09-05 15:37
Thank you, I will do that.

**Comment by zhimin-zeng-bambulab** [comment] 2023-09-06 06:54
Create a new issue  #2464 to track the issue of Select one part of the assembly individually for painting.

**Closed by zhimin-zeng-bambulab** 2023-09-06 06:54 UTC
Labels: bug
