### ISSUE TITLE
Filament preset settings not editable after switch tab in filament settings

### ISSUE THREAD

**Issue by gddrx** [bambulab/BambuStudio#3796] opened 2024-03-29 21:15 UTC
### Bambu Studio Version

1.9.0.60

### Where is the application from?

Bambu Lab github releases

### OS version

openSuSE Tumbleweed

### Printer

Bambulab P1S

### How to reproduce

1. Open BambuLab Studio app image (ubuntu or fedora version build)
2. Click "New project" or "Prepare"
3. Click icon "Click to edit preset"
4. All fine, on tab "Filament" - all settings editable
5. Click other tab (for example - Cooling)
6. And now after that on "Cooling" tab we can't edit values.
![2024-03-29_23-03](https://github.com/bambulab/BambuStudio/assets/97629/b00469d1-b8dd-4d4a-8714-5d2f6263629d)
7. Click to tab "Filament" - and most (95%) settings not editable (like unactive)
![2024-03-29_20-47](https://github.com/bambulab/BambuStudio/assets/97629/47c35320-a07d-4123-b1ad-84ada48753f3)

### Actual results

Cant edit values of filament settings.

### Expected results

Nothing. User can made changes to filament preset.

### Project file & Debug log uploads

[debug_.tar.gz](https://github.com/bambulab/BambuStudio/files/14808619/debug_.tar.gz)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by not-surt** [comment] 2024-03-30 02:38
Can confirm on same version 1.9.0.60 on P1S under Kubuntu 23.10.

**Comment by Edzi11** [comment] 2024-04-02 16:24
Can confirm this happens on windows as well. It wont let me edit filament profiles on my laptop but after doing a clean install on my desktop it works on here.

**Comment by mzient** [comment] 2024-04-04 07:40
This happens to me, too. I was able to edit the values on the 1st tab, but after switching to cooling the values were no longer editable. Even worse - after switching back to the 1stt tab, I could no longer edit most of the values (the 1st section was still editable).
Version: 1.9.0.60 (Bambu_Studio_linux_ubuntu_01.09.00.60.AppImage)
OS: Ubuntu 22.04
Printer: Bambu P1S

**Comment by mzient** [comment] 2024-04-27 17:14
# [1.9.1 Public Beta 4](https://github.com/bambulab/BambuStudio/releases/tag/v01.09.01.58)
Still bugged.

**Comment by OzDruiD** [comment] 2024-04-27 22:43
Very odd, I can do all this edting values, both in an existing custom filament., aa basic bambu preset filament, etc etc
Changed all the ffilament values here in filament, just random stupid values.
![image](https://github.com/bambulab/BambuStudio/assets/20792799/1fa8e248-2192-4071-81c1-3e840339ebb9)
Cooling
![image](https://github.com/bambulab/BambuStudio/assets/20792799/cff7f827-f4f6-4f60-be33-aae392749230)

**Comment by thoronaug** [comment] 2024-05-23 15:41
Same problem here in Manjaro Linux. Version 1.9.1.66 (Ubuntu Appimage).
I've deleted BambuStudio config directory and start over, but doesn't solve the issue.

Any workaround meanwhile?  Are you using an older version or another slicer?

**Comment by mzient** [comment] 2024-05-25 10:31
> Same problem here in Manjaro Linux. Version 1.9.1.66 (Ubuntu Appimage). I've deleted BambuStudio config directory and start over, but doesn't solve the issue.
> 
> Any workaround meanwhile? Are you using an older version or another slicer?

I just stick with 1.8.4 for the time being, although I'd really love to try 1.9 features.

Bambu team: Please hear us! The problem is apparently quite widespread on Linux!

**Comment by bambu123** [comment] 2024-06-12 04:19
Fixed in version 1.9.2.

**Closed by bambu123** 2024-06-12 04:19 UTC
Labels: bug
