### ISSUE TITLE
Mesh Booleans still not predictable...

### ISSUE THREAD

**Issue by tubbybtch** [bambulab/BambuStudio#2263] opened 2023-08-11 04:20 UTC
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

X1C w/AMS

### How to reproduce

1. Add Primitive -> Box
2. Add Primitive -> Cylinder
3. Select Both ->  Assemble
4. Mesh Boolean tool
5. Part 1 [Select] Box
6. Part 2 [Select] Cylinder
7. Difference tab
8. [Difference]

Resultant mesh is huge and distorted.

### Actual results

![image](https://github.com/bambulab/BambuStudio/assets/17971233/1d3bddc8-6ea0-4873-9ad3-9cc6defb1ea0)
![image](https://github.com/bambulab/BambuStudio/assets/17971233/399bf8fe-fb4a-462c-a05e-c8baa4f267bc)

### Expected results

The resultant mesh should be same dimensions as Part 1 with Part 2 removed.

### Project file & Debug log uploads

[Test.zip](https://github.com/bambulab/BambuStudio/files/12318584/Test.zip)

Video included...

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by dragon-eyes-bbl** [comment] 2023-08-11 10:36
Thanks for the report, I can replicate the issue here.
Will update you once the issue is fixed.

**Comment by dragon-eyes-bbl** [comment] 2023-08-11 11:42
The issue will be fixed in the next release. Thanks.

**Comment by SaltWei** [comment] 2023-08-17 00:16
Included in latest release https://github.com/bambulab/BambuStudio/releases/tag/v01.07.04.52.

**Closed by SaltWei** 2023-08-17 00:16 UTC
Labels: bug
