### ISSUE TITLE
Linux Version 

### ISSUE THREAD

**Issue by H4kunaM4tata** [bambulab/BambuStudio#318] opened 2022-09-24 01:54 UTC
When is the slicer Linux version gonna be released??

The AppImage like Cura and Prusa provide works more than well. No everyone uses Windows or Mac.

Thank you

**Comment by lanewei120** [comment] 2022-09-27 00:36
> When is the slicer Linux version gonna be released??
> 
> The AppImage like Cura and Prusa provide works more than well. No everyone uses Windows or Mac.
> 
> Thank you

we are working on linux version
as there are too many issues
we can not give a stable version in a short time

however, we will submit some patches which can let Bambu Studio work on linux firstly as soon as possible

**Comment by whiiiskyy** [comment] 2022-09-27 02:00
@lanewei120 is totally understandable since you guys might have bigger problems to solve.

It's good to know tho Linux version is around the corner. Having to use Windows PC to use the slicer is not good haha

Thank for the reply and solid work the team has been done so far.

**Comment by lanewei120** [comment] 2022-09-29 04:05
just submited the codes to supprt linux version

currently some known issues:
- a random crash when software launch(we can ignore it and retry until success)
- the liveview is not working

please refer to https://github.com/bambulab/BambuStudio/issues/12 for the details

**Comment by whiiiskyy** [comment] 2022-09-29 08:08
Thank you @lanewei120 🙌

**Comment by deftdawg** [comment] 2022-10-02 21:02
@whiiiskyy this should be closed as it's a dupe of #12

**Comment by whiiiskyy** [comment] 2022-10-02 23:32
> @whiiiskyy this should be closed as it's a dupe of #12 

Sure thing. Thank you

**Comment by deftdawg** [comment] 2022-10-02 23:47
You as the author of the issue can close it...🙂
(I'm not an admin, so it might end up sitting open until the admins do a clean up)

**Closed** 2022-11-10 06:50 UTC
Labels: feature

**Comment by meladori29** [comment] 2024-10-18 23:46
Any updates?  I got a Bambu printer and can't use it on any of my machines except the Handy app in my phone because the install on Linux has network issues. Bambu I would expect better 2 years later what is going on?

**Comment by lanewei120** [comment] 2024-10-19 01:28
@meladori29 

we have supported linux versions on github long time ago
please find it from https://github.com/bambulab/BambuStudio/releases

thanks

**Comment by meladori29** [comment] 2024-10-19 02:15
> @meladori29
> 
> we have supported linux versions on github long time ago please find it from https://github.com/bambulab/BambuStudio/releases
> 
> thanks

Yeah but the network file The studio asks you to download when you first install it says it installs but then it doesn't work you can't log into the bamboo studio and you can't send sliced files to the printer That's what I'm asking you to correct.
