### ISSUE TITLE
opening a model in bambu slicer reports a g-code path goes beyond plate boundaries

### ISSUE THREAD

**Issue by Shadoejack** [bambulab/BambuStudio#2256] opened 2023-08-10 14:46 UTC
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

windows 11 64 bit

### Additional system information

cpu 13 gen i9 113900hx  2.20 ghz
memory 64 gb ram
video geforce 4900 rtx

(Dell m18 r1 laptop)

### Printer

Bambu X1C

### How to reproduce

model from https://www.printables.com/model/348616-bambu-p1p-and-x1-sliding-vent-glass-top-enclosure-

download from 
(W) SLIDER v3_2 - LED - NEW REDESIGN
W-Full_Vent-4_V2.stl

open in bambu slicer I did 3 walls 20% gyroid infill

### Actual results

slice, throws error, tried fix model still threw error,  item is 199.016 x 182.67 x 43.014 and I tried to have it auto arrange the model on the plate as well same error persisted

opened same model in latest orce slicer 1.6.4-beta 2 and no such error

### Expected results

slicing and allowing me to print

### Project file & Debug log uploads

[W-Full_Vent-1_v2.zip](https://github.com/bambulab/BambuStudio/files/12313964/W-Full_Vent-1_v2.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by DeanDavis** [comment] 2023-08-10 20:44
This is a CRITICAL BUG!!!!
Here is the travel of one of my projects after pulling it up in 1.7.3.50

![Screen Shot 2023-08-10 at 4 42 12 PM](https://github.com/bambulab/BambuStudio/assets/12413449/16861c99-7879-4a8c-b542-440412869f4e)

I only noticed this AFTER my print head SLAMMED into the left side of the printer at full speed then slightly damaged by build plate.

I just started a new project and placed this object on the build plate and am getting the same result.

**Comment by DeanDavis** [comment] 2023-08-10 21:13
This might be of note. This object is on plate two.
My theory is that the travel algorithm is trying to travel over to plate one.
I'm doing a test right now but it looks like I don't have this issue if I slice only using plate 1.

**Comment by DeanDavis** [comment] 2023-08-10 21:21
I think that is almost certainly what is happening. Here is the travel on plate 2 superimposed over the grid of all plates. Doesn't match up exactly but it looks like plate 2 is trying to reach over to the purge tower of plate 1 for some reason.
![Screen Shot 2023-08-10 at 5 20 27 PM](https://github.com/bambulab/BambuStudio/assets/12413449/b0421ff6-1e9f-4dbd-b751-3577a8e48631)

**Comment by QingZhangBambu** [comment] 2023-08-11 01:48
@Shadoejack I didn't produce that. could you provide 3mf file? That would be helpful.
![image](https://github.com/bambulab/BambuStudio/assets/112676417/3ff71405-7b06-4db6-8465-9aaa0de8b7d5)

![image](https://github.com/bambulab/BambuStudio/assets/112676417/54041a50-b7b0-4898-af51-b94bae1284d8)
![image](https://github.com/bambulab/BambuStudio/assets/112676417/f2a1880d-a509-4003-a7df-b9c76c7f8d06)
![image](https://github.com/bambulab/BambuStudio/assets/112676417/963e20fc-badb-4ca6-9fba-c18dff560209)

**Comment by QingZhangBambu** [comment] 2023-08-11 01:49
@DeanDavis Could you provide your 3mf file, i will check it.

**Comment by Shadoejack** [comment] 2023-08-11 05:39
Generating it again now, and mine was only a single plate print.
[W-Full_Vent-4_V2 with error.zip](https://github.com/bambulab/BambuStudio/files/12318853/W-Full_Vent-4_V2.with.error.zip)

**Comment by DeanDavis** [comment] 2023-08-11 12:28
> @DeanDavis Could you provide your 3mf file, i will check it.

Don't need to it's super easy to re-create.
Running version 1.7.3.50

Start a new project
On plate 1 add a primitive cube. Slice it. Go down a few layers and force a color change by layer. So now you have a two color cube with a purge tower.

Add a second plate and repeat.
When you slice plate 2 the travel will reach to plate 1.
If you actually try to print plate two the print head will slam into the side of the printer at full speed as it tries to do this travel.

![Screen Shot 2023-08-11 at 8 27 55 AM](https://github.com/bambulab/BambuStudio/assets/12413449/ab49180a-b46e-4980-8910-b97d9348cbf7)

**Comment by DeanDavis** [comment] 2023-08-11 16:41
More info on this.
I have in my "Printer" Settings under "Extruder" tab the setting "Wipe While Retracting" UNCHECKED.

This seems to make a difference. When it is checked, which is the default, I do not see this issue.

**Comment by k8stuff** [comment] 2023-08-11 17:50
I can replicate the same : 

![image](https://github.com/bambulab/BambuStudio/assets/101044718/3ba471b6-1f5f-431c-b973-501d4090d6eb)

![image](https://github.com/bambulab/BambuStudio/assets/101044718/cae7f744-aa15-4dae-b305-56c546128539)

**Comment by SaltWei** [comment] 2023-08-14 11:57
Can reproduce this bug. Thanks everyone!

**Comment by SaltWei** [comment] 2023-08-14 12:25
> Can reproduce this bug. Thanks everyone!

And we have found the position of bug code. Very old bug...

**Comment by SaltWei** [comment] 2023-08-16 12:32
Fix patch has been published. Will be included in 1.7.4 release version as well.
Thank everyone for suggestion!

**Comment by SaltWei** [comment] 2023-08-17 00:16
Included in latest release https://github.com/bambulab/BambuStudio/releases/tag/v01.07.04.52.

**Comment by SaltWei** [comment] 2023-08-23 02:53
@QingZhangBambu 所以reopen原始问题谁看，你看嘛？

**Comment by tangketan** [comment] 2023-12-21 02:39
Offical 1.8 has been released and this file is sliced fine. Close this issue.

**Closed by tangketan** 2023-12-21 02:39 UTC
Labels: bug
