### ISSUE TITLE
K values don’t save on Italia Language 

### ISSUE THREAD

**Issue by djmarkino94** [bambulab/BambuStudio#2446] opened 2023-09-04 08:37 UTC
### Bambu Studio Version

01.07.04.52

### Where is the application from?

Bambu Lab github releases

### OS version

Mac OS Ventura 13.5.1

### Printer

Bambulab x1c combo

### How to reproduce

Insert k values on manage and it doesn't save them

### Actual results

The k value is not stored On italian language

### Expected results

the values ​​should be memorized as when bambu is in English

### Project file & Debug log uploads

Q

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment] 2023-09-05 01:56
@djmarkino94  Could you share your log file when you can't save it?

**Comment by djmarkino94** [comment] 2023-09-05 08:15
how should i do?Inviato da iPhoneIl giorno 5 set 2023, alle ore 03:56, zhimin-zeng-bambulab ***@***.***> ha scritto:﻿
@djmarkino94  Could you share your log file when you can't save it?

**Comment by djmarkino94** [comment] 2023-09-05 08:31
> @djmarkino94  Could you share your log file when you can't save it?

how should i do?

**Comment by zhimin-zeng-bambulab** [comment] 2023-09-05 08:59
![image](https://github.com/bambulab/BambuStudio/assets/120697589/4c518eef-db99-4f9f-833d-d88f2681b181)
@djmarkino94  First find the log folder, then find the log file corresponding to your current operation time.

**Comment by djmarkino94** [comment] 2023-09-05 09:46
Ok but how do I know which is the right log file to send? how do i know that log shows the error?

**Comment by zhimin-zeng-bambulab** [comment] 2023-09-05 09:57
1. You can delete all the original logs before starting the software, or backup them to other folders, so that the logs generated after you start the software are what you want.
2. After starting the software, reproduce this bug in the Italian environment, and then upload the newly generated log file to github. Let me take a look at the log file.

**Comment by djmarkino94** [comment] 2023-09-05 10:06
let me you know if its ok

**Comment by zhimin-zeng-bambulab** [comment] 2023-09-05 10:30
I found that when you saved the data, there is already a problem. Can you describe the steps to reproduce this problem in detail?

**Comment by djmarkino94** [comment] 2023-09-05 11:01
very simply when it is in English I can see the stored K values, when I switch to Italian the K values ​​are all zero and when I change them they return to zero, in practice it does not save them. I try to attach a video

**Comment by djmarkino94** [comment] 2023-09-05 11:05
[Senza nome.mov.zip](https://github.com/bambulab/BambuStudio/files/12522639/Senza.nome.mov.zip)

**Comment by djmarkino94** [comment] 2023-09-08 09:02
> I found that when you saved the data, there is already a problem. Can you describe the steps to reproduce this problem in detail? And what is the diameter of the nozzle you are using？

Hello News?

**Comment by sodachen22** [comment] 2023-09-09 07:34
Yes, we know the reason. The printer only support ".", but in Italian, "." is instead of ",". We will fix this issue. Please use English as a workaround before the new software with this fix.

**Comment by djmarkino94** [comment] 2023-09-09 08:09
> Yes, we know the reason. The printer only support ".", but in Italian, "." is instead of ",". We will fix this issue. Please use English as a workaround before the new software with this fix.

Thank you

**Comment by Witawat** [comment] 2023-09-17 14:58
i have problems in English Language

![image](https://github.com/bambulab/BambuStudio/assets/4926369/af9c9492-29a2-4d5c-ac8b-dc6a60f07dce)

[log.zip](https://github.com/bambulab/BambuStudio/files/12643068/log.zip)

**Comment by djmarkino94** [comment] 2023-10-10 09:49
- [ ] News?  I always have the same problem

**Comment by zhimin-zeng-bambulab** [comment] 2023-10-10 10:15
@djmarkino94  Please provide the Studio version and firmware version in which you still have this problem. Thanks!

**Comment by djmarkino94** [comment] 2023-10-10 11:19
> @djmarkino94 Please provide the Studio version and firmware version in which you still have this problem. Thanks!

Same problem, on Mac when I put the Italian Language the K value its all to 0, and if I try to modify dont'change.
<img width="745" alt="Screenshot 2023-10-10 alle 13 15 43" src="https://github.com/bambulab/BambuStudio/assets/111192738/433baf12-722b-4fd4-9458-338cda6f3f20">
<img width="553" alt="Screenshot 2023-10-10 alle 13 16 43" src="https://github.com/bambulab/BambuStudio/assets/111192738/ee2c7d60-7ba5-4050-b7c8-aee5b3b85fea">
![IMG_6132](https://github.com/bambulab/BambuStudio/assets/111192738/5e650ca3-579b-4e08-8474-49d06afa3ba2)

**Comment by zhimin-zeng-bambulab** [comment] 2023-10-13 08:37
maybe the same as #2689
@djmarkino94  It has been fixed in V1.7.7.89, you can have a try.

**Closed** 2023-10-13 09:07 UTC
Labels: bug, Printer
