### ISSUE TITLE
Speed slidebar constantly displayed

### ISSUE THREAD

**Issue by shughey00** [bambulab/BambuStudio#1469] opened 2023-03-12 16:39 UTC
**Describe the bug**
once I have activated the speed slidebar by changing the print speed it is constantly displayed in any program as in email..desktop etc. Seems that once the project starts to print if it is displayed it will not or cannot be minimized etc. The only way is to reboot Studio.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
1. slice project
2. send it to print plate
3. change speeds during or before a print starts
4.stuck visible

**Expected behavior**
Slidebar should never be stuck on visible without anyway to minimize it
![Screenshot (71)](https://user-images.githubusercontent.com/125712711/224558876-7439a414-e86b-46e5-b32e-fe565d996a69.png)
![Screenshot (72)](https://user-images.githubusercontent.com/125712711/224558877-ee0e1004-2d6f-40b6-931a-d06f95637e1e.png)

**Desktop (please complete the following information):**
 windows 64 bit windows 11

**Comment by walterwongbbl** [comment] 2023-03-22 02:13
Hi.
Do you still encounter this issue when using the latest bambu studio version.
Does this issue occur every time?

**Comment by shughey00** [comment] 2023-03-22 11:24
I am not sure about the latest firmware as I run the SoftFever version
which didn’t do it. Could always be a strange issue within windows even
though it’s latest windows 11 update

**Comment by shughey00** [comment] 2023-03-24 15:09
O.K..so it still does this. this is on two different computers running
windows 10 on one and windows 11 on the other. Does it in both Soft Fever
and the latest Bambu sliver version.
It seems to happen if youleave the window open while it finishes a job. It
seems to close o.k. during a job bot oe the job is complete you have to
close out the slicer and restart.
Scott

**Comment by walterwongbbl** [comment] 2023-04-06 12:19
Hi.
We cannot reproduce this problem, but we will try to fixed it.
Improvements will be included in the next release version

**Comment by shughey00** [comment] 2023-04-06 13:42
That’s fine. It is intermittent but has done it on two different devices.
Could be some odd glitch with certain other programs running in background
like say fusion 360 or something like that.

**Comment by Somerandomgithugguy** [comment] 2023-04-17 05:01
I have this problem too and was told it would be fixed in the next release. :)

**Comment by walterwongbbl** [comment] 2023-08-02 08:32
Hi.
Please use the latest version of Bambus Studio

**Closed** 2023-10-13 02:22 UTC
Labels: bug
