### ISSUE TITLE
Project Tab broken

### ISSUE THREAD

**Issue by RaySajuuk** [bambulab/BambuStudio#2343] opened 2023-08-19 20:32 UTC
### Bambu Studio Version

1.7.4

### Where is the application from?

Bambu Lab github releases

### OS version

macOS 13

### Printer

Bambu Lab X1CC

### How to reproduce

Open existing 3mf file/Import model file in new project.
Go to project tab.

### Actual results

Unable to edit any information
<img width="1515" alt="Screenshot 2023-08-19 at 1 37 35 PM" src="https://github.com/bambulab/BambuStudio/assets/1126364/10a348dc-8286-4399-a92e-6eaff51e1c0a">

### Expected results

Back in 1.5.x I was able to edit project information.
Bambu Wiki Page [https://wiki.bambulab.com/en/software/bambu-studio/project-resources](url)

![](https://wiki.bambulab.com/software/bambu-studio/project-resources/project_basic_info.png)

### Project file & Debug log uploads

[Project Info Test.3mf.zip](https://github.com/bambulab/BambuStudio/files/12386666/Project.Info.Test.3mf.zip)
[debug_Fri_Aug_18_21_35_06_5082.log.0.zip](https://github.com/bambulab/BambuStudio/files/12386667/debug_Fri_Aug_18_21_35_06_5082.log.0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by MadMax389** [comment] 2023-08-19 21:47
Please bring back the project tab. I miss it!

**Comment by lanewei120** [comment] 2023-08-21 02:39
we are re-design this logic, and hope it will come out soon

**Comment by RaySajuuk** [comment] 2023-08-21 10:10
> we are re-design this logic, and hope it will come out soon

If the function is not working why don't temporarily remove it or at least add some type of notice on the tab or wiki. The lack of proper communication is frustrating, the time I spent on trying to figure out what is wrong on my end was completely wasteful. Please be respectful to all the users in the community that actively trying to support you guys. Thanks.

**Comment by cpasoft** [comment] 2023-09-25 08:57
One month later, no news and the tab still not working...

**Comment by YifanWuBambu** [comment] 2023-10-10 05:36
Hi @RaySajuuk 
The project tab in bambu studio is now read only.
It displays information of the models downloaded from MakerWorld.
![273785531-b2b4c432-81b6-4226-b80c-ef34f81e99ef](https://github.com/bambulab/BambuStudio/assets/110661856/daecd069-041a-46f5-934e-ba21bb2c4993)
![273785566-cb5d93b0-5812-4f86-98bb-d1bd96951cfb](https://github.com/bambulab/BambuStudio/assets/110661856/f0575672-e686-4988-bdf1-01c763dad28d)
![273785576-1fa82881-8ac7-4d3c-9ad8-5384b1d220b4](https://github.com/bambulab/BambuStudio/assets/110661856/bc48a7e2-76a4-4a3e-8519-e7ea829af2ad)


If you want to insert informations into your 3mf, please upload the 3mf as a model in makerworld.com.
When it is published, you may download the 3mf from the model page and all informations will be added to the 3mf.

If you do not want others see the 3mf, you may set it as private visibility.
![273786026-0ada1d94-b398-48df-a9b6-7cdb43d11da2](https://github.com/bambulab/BambuStudio/assets/110661856/63c4b408-08e6-4338-b8bf-c75cdac8f48a)

**Comment by RaySajuuk** [comment] 2023-10-13 00:10
> Hi @RaySajuuk The project tab in bambu studio is now read only. It displays information of the models downloaded from MakerWorld. ![273785531-b2b4c432-81b6-4226-b80c-ef34f81e99ef](https://user-images.githubusercontent.com/110661856/273786562-daecd069-041a-46f5-934e-ba21bb2c4993.png) ![273785566-cb5d93b0-5812-4f86-98bb-d1bd96951cfb](https://user-images.githubusercontent.com/110661856/273786571-f0575672-e686-4988-bdf1-01c763dad28d.png) ![273785576-1fa82881-8ac7-4d3c-9ad8-5384b1d220b4](https://user-images.githubusercontent.com/110661856/273786580-bc48a7e2-76a4-4a3e-8519-e7ea829af2ad.png)
> 
> If you want to insert informations into your 3mf, please upload the 3mf as a model in makerworld.com. When it is published, you may download the 3mf from the model page and all informations will be added to the 3mf.
> 
> If you do not want others see the 3mf, you may set it as private visibility. ![273786026-0ada1d94-b398-48df-a9b6-7cdb43d11da2](https://user-images.githubusercontent.com/110661856/273786597-63c4b408-08e6-4338-b8bf-c75cdac8f48a.png)

@YifanWuBambu This is nice to change to see. I do the fully functioned project information editor comes back soon. It is nice to have the integration with MakerWorld, which I assumed it will be the case. It is also a very useful tool beyond the current read-only for MakerWorld models.

**Comment by lanewei120** [comment] 2023-10-24 02:02
close this issue as the solution is published

**Closed by lanewei120** 2023-10-24 02:02 UTC
Labels: bug

**Comment by MadMax389** [comment] 2023-10-24 11:19
I hope this is not the permanent "fix" for this function. I still cannot edit or add any information in the project tab. I lack the ability to add or change the order of any picture, set the cover photo or add text or pdf files. The aspect ratio of the cover picture is way off. To me, it is impractical to upload the profile to MW and then download it. I always modify my uploaded profiles with standard printer/filament profiles to pass the upload screening test, but prefer to keep my local copies with my own modified profiles. I always delete the downloaded copies.

**Comment by RegexRiddler** [comment] 2023-10-27 16:15
@lanewei120 How can you call that a solution? The issue is that we can't write that information directly in the project tab in Bambu Studio, forcing the users to upload the files to MakerWorld and then download them again isn't a solution at all.

As a product developer I cannot upload any of my files to any services no matter how "private" they are. And even for personal projects, if I make changes to the models I then have to re-upload the new file and then download it again.
