### ISSUE TITLE
Refresh/Reload Imported Models [Feature Request]

### ISSUE THREAD

**Issue by CS-Account** [bambulab/BambuStudio#334] opened 2022-09-27 21:09 UTC
In Cura and other slicers you can reload all models from file. This is useful as often times when trying to print complex designs, you might need to make quick iterations where you do not want to have to add in parts and move and orient them all over again with every iteration.

Having a refresh button to reload changes to files without needing to reload would be a very useful feature to have accessible.

**Comment by RobinWhitfield** [comment] 2022-09-28 11:42
Duplicate of #189

**Comment by YifanWuBambu** [comment] 2022-10-21 01:46
Added in v1.3.0.12.

**Closed by YifanWuBambu** 2022-10-21 01:46 UTC
Labels: feature
